const mongoose=require('mongoose');
const Product=require('./Product');
const User=require('./User');

const orderItemSchema=mongoose.Schema({
    productId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:Product,
        required:true,
    },
    name:{
        type:String,
        required:true,
    },
    image:{
        type:String,
        required:true,
    },
    price:{
        type:String,
        required:true,
    },
    size:String,
    color:String,
    quantity:{
        type:Number,
        required:true,
    }
},{
    _id:false,
});

const orderSchema=mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:User,
        required:true,
    },
    orderItems:{
        type:[orderItemSchema],
        required:true,
    },
    shippingAddress:{
        type:{
            address:{
                type:String,
                required:true,
            },
            city:{
                type:String,
                required:true,
            },
            postalcode:{
                type:String,
                required:true,
            },
            country:{
                type:String,
                required:true,
            },
        },
        required:true,
    },
    paymentMethod:{
        type:String,
        required:true,
    },
    totalPrice:{
        type:Number,
        required:true,
    },
    isPaid:{
        type:Boolean,
        default:false,
    },
    paidAt:Date,
    isDelivered:{
        type:Boolean,
        default:false,
    },
    deliveredAt:Date,
    paymentStatus:{
        type:String,
        default:"pending",
    },
    status:{
        type:String,
        enum:["Processing","Delivered","Shipped","Cancelled"],
        default:"Processing",
    },
},{
    timestamps:true
});

module.exports=mongoose.model('Order',orderSchema);